export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
            <h3>This is blog header</h3>
            <body>{children}</body>
            <footer>This is blog footer</footer>
        </>
    )
  }
  